spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5454/hoteldb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

