spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5454/hoteldb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

security:
  oauth2:
    resourceserver:
      jwt:
        issue-uri: http://localhost:9001/realms/hotel-booking

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

